import math
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

variable_explanation_dict = {
    "hotel_name": "",
    "bookingshare": "Booking popularity percentage",
    "pricepernight": "",
    "rating": "",
    "ratingscount": "Number of guest reviews",
    "starcategory": "",
    "mealtype": "",
    "cancelable": "",
    "distancetoreference": "",
    "distancetocity": "",
    "distancetounderground": "Distance to metro station",
    "distancetobeach": "",
    "distancetoairport": "",
    "roomcategory": "",
    "price": "Total stay cost",
    "24_stunden_rezeption": "",
    "24_stunden_sicherheitspersonal": "",
    "abendessen": "",
    "abenteuer": "",
    "adapterorladegeräte": "",
    "aerobic": "",
    "american__express": "",
    "animation__(erwachsene)": "",
    "aparthotel": "",
    "arabisch": "",
    "arbeitsbereich__für__arbeit__mit__laptop__geeignet": "Laptop-friendly workspace",
    "assistenztiere__sind__von__gebührenor__restriktionen__ausgeschlossen": "Service animals exempt from fees",
    "aufdeckservice": "",
    "aufzug": "",
    "ausflugsinformationen": "",
    "ausgewiesene__raucherbereiche": "",
    "autovermietung": "",
    "außenpool": "",
    "außenpool__(saisonal)": "",
    "baby_or__kinderbetreuung": "",
    "babybadewanne": "",
    "backofen": "",
    "bademantel": "",
    "badewanne__oder__dusche": "",
    "balkon": "",
    "bankettsaal": "",
    "bar": "",
    "barrierefrei": "",
    "barrierefreie__dusche": "",
    "beheizter__pool": "",
    "behindertenfreundlich": "",
    "behindertengerechte__parkplätze": "",
    "besichtigungstouren": "",
    "bestätigte__corona_schutzmaßnahmen": "",
    "betreute__kinderaktivitäten": "",
    "bettwäsche": "",
    "bibliothek": "",
    "bidet": "",
    "billard": "",
    "bosnisch": "",
    "boutique_ordesignhotel": "",
    "boutiquenorläden": "",
    "brettspieleorpuzzle": "",
    "budgetorientiert": "",
    "buggys": "",
    "businesscenter": "",
    "businesshotel": "",
    "bücher": "",
    "bügeleinrichtungen": "",
    "bügelservice": "",
    "café": "",
    "cash__(bargeld)": "",
    "computerarbeitsplatz": "",
    "concierge__service": "",
    "dachterrasse": "",
    "dampfbad": "",
    "darts": "",
    "daunenkissen": "",
    "deckenventilator": "",
    "desinfektion__von__geschirr": "",
    "deutsch": "",
    "diners__club": "",
    "discover": "",
    "dusch_badewannen__kombination": "",
    "dusche": "",
    "duschhocker": "",
    "eigenes__badezimmer": "",
    "einzeln__verpackte__essenspakete__verfügbar": "",
    "englisch": "",
    "espressomaschine": "",
    "essbereich": "",
    "essen__kann__auf__das__zimmer__geliefert__werden": "",
    "esstisch": "",
    "eurocardormastercard": "",
    "express_check_inor_out": "",
    "fahrradstellplatz": "",
    "fahrradtouren": "",
    "fahrradvermietung": "",
    "familie": "",
    "familienzimmer__vorhanden": "",
    "faxorkopierer": "",
    "feuerlöscher": "",
    "filme": "",
    "fitness": "",
    "fitnesseinrichtung": "",
    "flachbild_tv": "",
    "flughafenshuttle": "",
    "französisch": "",
    "friseur_orschönheitssalon": "",
    "frühstück": "",
    "frühstücksbuffet": "",
    "futternapf": "",
    "fußbad": "",
    "fußmassage": "",
    "föhn": "",
    "ganzkörpermassage": "",
    "ganzkörperpackung": "",
    "garten": "",
    "gast__kann__zimmerreinigung__abmelden": "Opt-out housekeeping available",
    "gasthaus": "",
    "gefrierschrank": "",
    "geldautomat__vor__ort": "",
    "geldwechsel": "",
    "gemeinschaftsbad": "",
    "gemeinschaftsküche": "",
    "gemeinschaftsloungeortv_bereich": "",
    "gepäckaufbewahrung": "",
    "gesamte__wohneinheit__im__erdgeschoß": "Ground floor unit",
    "gesamte__wohneinheit__ist__rollstuhlgerecht": "Fully wheelchair accessible",
    "geschenkeladenor__zeitungsstand": "",
    "geschirr__für__kinder": "",
    "gesicherte__fahrradstellplätze": "",
    "gesicherte__parkplätze": "",
    "gesichtsbehandlungen": "",
    "getränkeorsnackautomat": "",
    "golforsport": "",
    "golfplatz__(max.__3__km__entfernt)": "",
    "golfunterricht": "",
    "grillmöglichkeiten": "",
    "gäste__werden__auf__gesundheit__kontrolliert": "",
    "haarentfernung__mit__wachs": "",
    "halboffenes__badezimmer": "",
    "handmassage": "",
    "handschuhe__für__gäste__verfügbar": "",
    "handtücher": "",
    "hausschuhe": "",
    "haustiere__erlaubt": "",
    "haustierfreundliches__hotel": "",
    "heizung": "",
    "heizung__im__zimmer__steuerbar": "Room-controlled heating",
    "heiße__quelle": "",
    "hochzeitsservice": "",
    "hotel": "",
    "hundeauslaufplatz": "",
    "hydromassage__dusche": "",
    "hypoallergene__bettware__erhältlich": "",
    "höheres__wc": "",
    "hörhilfen": "",
    "individuell__dekoriert__je__zimmer": "",
    "individuelle__möbel__je__zimmer": "Custom furniture per room",
    "infinity_pool": "",
    "innenpool": "",
    "innenpool__(saisonal)": "",
    "investitionen__in__lokale__nachhaltigkeitsprojekte": "Local sustainability investments",
    "italienisch": "",
    "jcb": "",
    "japanisch": "",
    "kabel__tv": "",
    "kaffeeortee__in__gemeinschaftsräumen": "",
    "kanusport": "",
    "kapelleorschrein": "",
    "karaoke": "",
    "keine__corona_schutzmaßnahmen": "",
    "keine__oder__eingeschränkte__verwendung__von__plastik_artikeln__(z.b.__strohhalme,__besteck__oder__einweg_artikel)": "Limited plastic use",
    "kinder_orbabybetten__auf__anfrage": "",
    "kinderbecken": "",
    "kinderbetreuung__im__zimmer": "",
    "kinderbücher": "",
    "kinderclub": "",
    "kinderfreundliches__buffet": "",
    "kinderhochstuhl": "",
    "kindermahlzeiten": "",
    "kinderspielplatz": "",
    "kissenauswahl": "",
    "kitchenette": "",
    "klimaanlage__im__zimmer": "",
    "klimaanlage__im__zimmer__steuerbar": "Room-controlled air conditioning",
    "klimaanlage__in__allen__zimmern": "",
    "kochplattenor__herd": "",
    "kochutensilien": "",
    "konferenz___und__veranstaltungsräume": "",
    "kontaktlose__bezahlung": "",
    "kontaktloser__check_inorout": "",
    "kontinentales__frühstück": "",
    "kopfmassage": "",
    "kostenlos__parken__vor__ort": "",
    "kostenloses__handdesinfektionsmittel": "",
    "kroatisch": "",
    "kunstgalerie__im__hotel": "",
    "körperpeeling": "",
    "küche": "",
    "kühl_gefrierkombination": "",
    "kühlschrank": "",
    "kühlschrank__im__gemeinschaftsbereich": "",
    "lan": "",
    "lgbt_freundlich": "",
    "ladestation__für__elektro_autos": "",
    "langzeitparken": "",
    "lebensmittel__aus__biologischem__anbau": "",
    "lebensmittel__aus__der__region": "",
    "live_musikorperformance": "",
    "lokale__karten": "",
    "lunchpakete": "",
    "luxushotel": "",
    "maestro": "",
    "maniküre": "",
    "masken__für__gäste__verfügbar": "",
    "maskenpflicht": "",
    "massage": "",
    "massage__im__zimmer": "",
    "massagestuhl": "",
    "maßnahmen__zur__reduzierung__des__energieverbrauchs": "Energy conservation measures",
    "mehrsprachiges__personal": "",
    "mikrowelle": "",
    "mikrowelle__im__gemeinschaftsbereich": "",
    "mini_kühlschrank": "",
    "minibar": "",
    "minigolf": "",
    "minimarkt__vor__ort": "",
    "mitarbeiter__folgen__regeln__des__regionalen__standards": "Staff follows regional standards",
    "mitarbeiter__tragen__schutzkleidung": "",
    "motto_dinnerabende": "",
    "nachhaltige__unterkunft": "",
    "nachtclubordj": "",
    "nackenmassage": "",
    "nicht__rollstuhlgerecht": "",
    "nichtraucherunterkunft": "",
    "nichtraucherzimmer": "",
    "nichtschwimmerbereich": "",
    "niederländisch": "",
    "niedriges__waschbecken": "",
    "niedriges__waschbecken__im__bad": "",
    "notrufleine__im__bad": "",
    "nur__assistenztiere__sind__erlaubt": "",
    "nur__hunde__sind__erlaubt": "",
    "nur__hunde__und__katzen__sind__erlaubt": "",
    "nur__für__erwachsene": "",
    "obere__stockwerke__mit__fahrstuhl__erreichbar": "",
    "outdoorspielgeräte__für__kinder": "",
    "paarmassage": "",
    "panoramahotel": "",
    "parken__vor__ort": "",
    "parkhausortiefgarage": "",
    "parkplatz__außerhalb__des__hotelgeländes": "",
    "parkservice": "",
    "pediküre": "",
    "pension": "",
    "pflegeprodukte": "",
    "picknickbereich": "",
    "pillow_top__matratze": "",
    "polnisch": "",
    "pool": "",
    "pool__cabana": "",
    "pool__mit__rampe": "",
    "pool_orstrandtücher": "",
    "poolbar": "",
    "portierorhotelpage": "",
    "portugiesisch": "",
    "premium__bettwaren": "",
    "privater__check_inor_out": "",
    "privater__strand": "",
    "privates__abendessen": "",
    "privates__tauchbecken": "",
    "privatstrand__in__der__nähe": "",
    "programm__zur__reduzierung__von__lebensmittelabfällen": "Food waste reduction program",
    "pub__crawl": "",
    "radfahren": "",
    "raucher__und__nichtraucherzimmer": "",
    "raucherzimmer": "",
    "rauchmelder": "",
    "recycling": "",
    "regendusche": "",
    "reinigung__mit__desinfektionsmittel": "",
    "reinigungsmittel__gegen__coronaviren": "",
    "reiseführer__oder__empfehlungen": "",
    "reiten": "",
    "resort": "",
    "restaurant": "",
    "rezeption": "",
    "rollstuhlgerecht": "",
    "rollstühle__verfügbar": "",
    "romantikorflitterwochen": "",
    "rumänisch": "",
    "russisch": "",
    "räumliche__trennung__von__gästen__und__mitarbeitern__in__hauptkontaktzonen": "Guest-staff physical separation",
    "rückenmassage": "",
    "safe__an__der__rezeption": "",
    "safe__im__zimmer": "",
    "safe__in__laptopgröße": "",
    "satelliten_tv": "",
    "sauna": "",
    "schallisolierung": "",
    "schlafsofa": "",
    "schlafzimmer": "",
    "schließfächer": "",
    "schrank": "",
    "schreibtisch": "",
    "schutzkleidung__für__gäste__verfügbar": "",
    "schwimmbad": "",
    "seife": "",
    "serbisch": "",
    "shampoo": "",
    "shopping": "",
    "shuttle__in__die__umgebung": "",
    "shuttle__zum__bahnhof": "",
    "shuttle__zur__fähre": "",
    "shuttleservice": "",
    "sicherheitsalarm": "",
    "sitzecke": "",
    "slowakisch": "",
    "smart__tv": "",
    "snackbar": "",
    "social__distancing__maßnahmen": "",
    "solarium": "",
    "sonnenschirme": "",
    "sonnenstühleor_liegen": "",
    "spa__&__wellnesscenter": "",
    "spa_anwendungen": "",
    "spaorentspannung": "",
    "spanisch": "",
    "speisen__für__spezielle__ernährungsbedürfnisse": "Special diet options",
    "spielbereich": "",
    "spiele__für__kinder": "",
    "spielhalle": "",
    "spielzeug": "",
    "spülmaschine": "",
    "strand": "",
    "strand__cabana": "",
    "strandbar": "",
    "strandhotel": "",
    "streaming_dienste__(z.b.__netflix)": "",
    "streaming_service": "",
    "strom__aus__erneuerbaren__energien": "",
    "städtereise": "",
    "tv": "",
    "tagesbett": "",
    "tauchbecken": "",
    "tee_orkaffeezubereiter": "",
    "teile__des__co²_ausstoßes__werden__durch__zertifikate__ausgeglichen": "Carbon offset program",
    "telefon": "",
    "tennisausrüstung": "",
    "tennisplatz": "",
    "terrasse": "",
    "thailändisch": "",
    "ticketservice": "",
    "tierkörbchen": "",
    "tischtennis": "",
    "toilettenpapier": "",
    "tourenorkurse__über__die__örtliche__kultur": "Local culture tours/classes",
    "tschechisch": "",
    "ungarisch": "",
    "unterkunft__wird__von__professionellem__reinigungsservice__gereinigt": "Professional cleaning service",
    "vegan": "",
    "vegetarisch": "",
    "ventilator": "",
    "verandaorterrasse": "",
    "verdunkelungsvorhänge": "",
    "versiegelung__des__raums__nach__reinigung": "",
    "videoüberwachung__der__außenbereiche__der__unterkunft": "Exterior video surveillance",
    "videoüberwachung__in__gemeinschaftsbereichen": "Common area surveillance",
    "visa": "",
    "visuelle__hilfe:__braille": "",
    "visuelle__hilfe:__fühlbare__zeichen": "Tactile signs",
    "vollwertiges__frühstück": "",
    "wc__mit__haltegriffen": "",
    "wlan": "",
    "wandern": "",
    "waschsalonorwäscheservice": "",
    "wassereinsparende__badezimmer_einrichtungen": "Water-saving bathroom fixtures",
    "wasserkocher": "",
    "wasserpark": "",
    "wasserrutsche": "",
    "wasserspielzeug__für__kinder": "",
    "wassersportmöglichkeiten__vor__ort": "",
    "wellness": "",
    "wellnessangebote": "",
    "wellnessbehandlungsraumor_räume": "",
    "wellnesshotel": "",
    "wellnessloungeorruhebereich": "",
    "whirlpool": "",
    "whirlpool_badewanne": "",
    "whirlpoolorjacuzzi": "",
    "wickeltisch": "",
    "wohnzimmer": "",
    "wäsche__wird__nach__regionalem__standard__gewaschen": "Regional laundry standards",
    "yoga": "",
    "zahnbürste": "",
    "zeitlicher__abstand__zwischen__aufenthalten__von__gästen__eingeführt": "Guest stay buffer period",
    "zeitung": "",
    "zeitungen__in__der__lobby": "",
    "zimmer__mit__verbindungstür": "",
    "zimmerreinigung": "",
    "zimmerreinigung__(eingeschränkt)": "",
    "zimmerservice": "",
    "zimmerservice__(eingeschränkt)": "",
    "zugang__über__außengelegene__gänge": "",
    "zustellbett__auf__anfrage": "",
    "zustellbetten": "",
    "direkter__strandzugang__(privater__strand)": "",
    "ipod_dockingstation": "",
    "ländlich": "",
    "übergroße__badewanne": "",
}


def generate_features(hotels: dict[str, dict[str, object]]) -> dict[str, any]:
    filter_out = [
        "searchid",
        "clusterchain",
        "clusterbrand",
        "clustersubbrand",
        "roomcategoryid",
        "requesttimestamp",
        "daystostart_bucket",
        "locationid",
        "clusterid",
        "deviceoutput",
        "ltr_score",
        "bookingshare",
    ]
    features = {}

    for row in hotels.values():
        for key, value in row.items():
            if key in filter_out or value is None:
                continue
            if key.startswith("amenity_"):
                key = key.replace("amenity_", "")

            key = key.lower().replace(" ", "_").replace("/", "or").replace("-", "_")

            if isinstance(value, bool) or (
                isinstance(value, int) and (value == 1 or value == 0 and key != "wlan")
            ):
                features[key] = True
            elif isinstance(value, float) or isinstance(value, int):
                if key not in features:
                    features[key] = (math.inf, -math.inf)
                try:
                    features[key] = (
                        min(features[key][0], value),
                        max(features[key][1], value),
                    )
                except:
                    print(f"Error with {key} and {value}")
            elif isinstance(value, str):
                if key == "hotel_name":
                    features[key] = ""
                    continue
                if key not in features:
                    features[key] = set()
                features[key].add(value)
            else:
                raise ValueError(f"Unexpected value type: {type(value)} for key: {key}")

    filtered_features = {}
    for key, value in features.items():
        if isinstance(value, set) and len(value) == 0:
            filtered_features[key] = ""
        elif isinstance(value, set) and len(value) == 1:
            continue
        elif isinstance(value, tuple) and (
            (value[0] == math.inf and value[1] == -math.inf) or (value[0] == value[1])
        ):
            continue
        else:
            filtered_features[key] = value

    return filtered_features


def generate_values(
    hotels: dict[str, dict[str, object]], features: dict[str, any]
) -> dict[str, dict[str, any]]:
    hotel_values = {}
    for hotel_name, hotel_data in hotels.items():
        hotel_values[hotel_name] = {}
        for key, value in hotel_data.items():
            if key.startswith("amenity_"):
                key = key.replace("amenity_", "")
            key = key.lower().replace(" ", "_").replace("/", "_or_").replace("-", "_")

            if key in features.keys():
                if isinstance(features[key], set):
                    hotel_values[hotel_name][key] = str(value)
                elif isinstance(features[key], tuple):
                    hotel_values[hotel_name][key] = float(value)
                elif isinstance(features[key], bool):
                    hotel_values[hotel_name][key] = bool(value)
                else:
                    hotel_values[hotel_name][key] = value
    assert len(hotel_values) == len(
        hotels
    ), "Hotel values and hotels have different lengths"
    return hotel_values
